<?php

namespace App\Controller;

use App\Entity\Producto;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class AddController extends AbstractController
{
    /**
     * @Route("/add", name="add")
     */
    public function index(EntityManagerInterface $entityManager)
    {
        foreach($this->productos as $key => $value){
            foreach($value as $producto){
                $articulo=new Producto();
                $articulo->setTipo($key);
                $articulo->setNombre($producto['nombre']);
                $articulo->setProcesador($producto['procesador']);
                $articulo->setPantalla($producto['pantalla']);
                $articulo->setCamara($producto['camara']);
                $articulo->setBateria($producto['bateria']);
                $articulo->setConectividad($producto['conectividad']);
                $articulo->setImagen($producto['imagen']);

                $entityManager->persist($articulo);
            }

        }
        $entityManager->flush();

        return $this->render('add/index.html.twig', [
            'controller_name' => 'AddController',
        ]);
    }
    private $productos=[
        'moviles' => [
            [   'id' => '1',
                'tipo' => 'movil',
                'nombre' => 'iPhone 12',
                'procesador' => 'A12',
                'pantalla' => 'FHD',
                'camara' => '12 MP',
                'bateria' => '2000',
                'conectividad' => '4G',
                'imagen' => 'images/iphone12.jpg',
            ],
            [   'id' => '2',
                'tipo' => 'movil',
                'nombre' => 'Poco F2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/f2pro.jpg',
            ],
            [   'id' => '3',
                'tipo' => 'movil',
                'nombre' => 'Huawei Mate 40 Pro',
                'procesador' => 'Kirin 990',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4100',
                'conectividad' => '5G',
                'imagen' => 'images/mate40pro.jpg',
            ],
            [   'id' => '4',
                'tipo' => 'movil',
                'nombre' => 'Xiaomi Mi 10 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '108 MP',
                'bateria' => '4000',
                'conectividad' => '5G',
                'imagen' => 'images/mi10pro.jpg',
            ],
            [   'id' => '5',
                'tipo' => 'movil',
                'nombre' => 'OnePlus 8 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '48 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/oneplus8.jpg',
            ],
            [   'id' => '6',
                'tipo' => 'movil',
                'nombre' => 'Samsung Note 20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/n20.jpg',
            ],
            [   'id' => '7',
                'tipo' => 'movil',
                'nombre' => 'Samsung S20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/s20.jpg',
            ],
            [   'id' => '8',
                'tipo' => 'movil',
                'nombre' => 'Oppo Find X2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '64 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/findx2pro.jpg',
            ],
            [   'id' => '9',
                'tipo' => 'movil',
                'nombre' => 'Sony Mark II',
                'procesador' => 'SD 865',
                'pantalla' => '4K',
                'camara' => '12 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/mark2.jpg'],
        ],
        'tablets' => [
            [   'id' => '10',
                'tipo' => 'tablet',
                'nombre' => 'iPhone 12',
                'procesador' => 'A12',
                'pantalla' => 'FHD',
                'camara' => '12 MP',
                'bateria' => '2000',
                'conectividad' => '4G',
                'imagen' => 'images/portfolio-imagen1.jpg',
            ],
            [   'id' => '11',
                'tipo' => 'tablet',
                'nombre' => 'Poco F2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/f2pro.jpg',
            ],
            [   'id' => '12',
                'tipo' => 'tablet',
                'nombre' => 'Huawei Mate 40 Pro',
                'procesador' => 'Kirin 990',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4100',
                'conectividad' => '5G',
                'imagen' => 'images/mate40pro.jpg',
            ],
            [   'id' => '13',
                'tipo' => 'tablet',
                'nombre' => 'Xiaomi Mi 10 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '108 MP',
                'bateria' => '4000',
                'conectividad' => '5G',
                'imagen' => 'images/mi10pro.jpg',
            ],
            [   'id' => '14',
                'tipo' => 'tablet',
                'nombre' => 'OnePlus 8 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '48 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/oneplus8.jpg',
            ],
            [   'id' => '15',
                'tipo' => 'tablet',
                'nombre' => 'Samsung Note 20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/n20.jpg',
            ],
            [   'id' => '16',
                'tipo' => 'tablet',
                'nombre' => 'Samsung S20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/s20.jpg',
            ],
            [   'id' => '17',
                'tipo' => 'tablet',
                'nombre' => 'Oppo Find X2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '64 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/findx2pro.jpg',
            ],
            [   'id' => '18',
                'tipo' => 'tablet',
                'nombre' => 'Sony Mark II',
                'procesador' => 'SD 865',
                'pantalla' => '4K',
                'camara' => '12 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/mark2.jpg'],
        ],
        'ordenadores' => [
            [   'id' => '19',
                'tipo' => 'pc',
                'nombre' => 'iPhone 12',
                'procesador' => 'A12',
                'pantalla' => 'FHD',
                'camara' => '12 MP',
                'bateria' => '2000',
                'conectividad' => '4G',
                'imagen' => 'images/iphone12.jpg',
            ],
            [   'id' => '20',
                'tipo' => 'pc',
                'nombre' => 'Poco F2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/f2pro.jpg',
            ],
            [   'id' => '21',
                'tipo' => 'pc',
                'nombre' => 'Huawei Mate 40 Pro',
                'procesador' => 'Kirin 990',
                'pantalla' => 'FHD',
                'camara' => '48 MP',
                'bateria' => '4100',
                'conectividad' => '5G',
                'imagen' => 'images/mate40pro.jpg',
            ],
            [   'id' => '22',
                'tipo' => 'pc',
                'nombre' => 'Xiaomi Mi 10 Pro',
                'procesador' => 'SD 865',
                'pantalla' => 'FHD',
                'camara' => '108 MP',
                'bateria' => '4000',
                'conectividad' => '5G',
                'imagen' => 'images/mi10pro.jpg',
            ],
            [   'id' => '23',
                'tipo' => 'pc',
                'nombre' => 'OnePlus 8 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '48 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/oneplus8.jpg',
            ],
            [   'id' => '24',
                'tipo' => 'pc',
                'nombre' => 'Samsung Note 20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/n20.jpg',
            ],
            [   'id' => '25',
                'tipo' => 'pc',
                'nombre' => 'Samsung S20',
                'procesador' => 'Exynos',
                'pantalla' => '2K',
                'camara' => '108 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/s20.jpg',
            ],
            [   'id' => '26',
                'tipo' => 'pc',
                'nombre' => 'Oppo Find X2 Pro',
                'procesador' => 'SD 865',
                'pantalla' => '2K',
                'camara' => '64 MP',
                'bateria' => '4500',
                'conectividad' => '5G',
                'imagen' => 'images/findx2pro.jpg',
            ],
            [   'id' => '27',
                'tipo' => 'pc',
                'nombre' => 'Sony Mark II',
                'procesador' => 'SD 865',
                'pantalla' => '4K',
                'camara' => '12 MP',
                'bateria' => '4000',
                'conectividad' => '4G',
                'imagen' => 'images/mark2.jpg'],
        ],
    ];
}
